---
- name: Backup Device Configurations
  hosts: sites_container_lab
  gather_facts: false
  connection: network_cli

  vars: 
    backup_root: ./backups

  tasks:
    - name: run show running-config on remote devices
      eos_command:
        commands: "show running-config"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes

    - name: ensure device folder is created
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}"
        state: directory

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: get/copy backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"