---
- name: Gather Arista EOS Facts
  hosts: sites_container_lab
  connection: network_cli
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Gather all legacy facts
      arista.eos.eos_facts:
        gather_subset: all
      register: device_facts    

    - name: Generate Markdown report of device information
      template:
        src: "./reports/report_template.j2"
        dest: "./reports/device_report.md"