---
- name: Generate Device Report
  hosts: sites_container_lab
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Gather Device Facts For Report
      arista.eos.eos_facts:
        gather_subset: all   

    - name: Generate Markdown Report Using Device Facts
      template:
        src: "./reports/report_template.j2"
        dest: "./reports/device_report.md"