---
- name: Get Intended Device Confifs From NetBox
  connection: local
  hosts: sites_container_lab
  gather_facts: False

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
    intended_configs_root: ./intended_configs

  tasks:
    - name: Get Device Details
      uri:
          url: "{{ netbox_url }}api/dcim/devices/?name={{ inventory_hostname }}"
          method: GET
          return_content: yes
          headers:
              accept: "application/json"
              Authorization: "Token {{ netbox_token }}"
      register: device

    - name: Get intended Device Config
      uri:
          url: "{{ netbox_url }}api/dcim/devices/{{ device.json.results.0['id'] }}/render-config/"
          method: POST
          return_content: yes
          headers:
              accept: "application/json"
              Authorization: "Token {{ netbox_token }}"
      register: intended_config

    - name: ensure intended configs folder is created
      file:
        path: "{{ intended_configs_root }}"
        state: directory
      run_once: yes

    - name: ensure device folder is created
      file:
        path: "{{ intended_configs_root }}/{{ inventory_hostname }}"
        state: directory

    - name: copy renedered config to folder
      copy:
        content: "{{ intended_config.json.content }}"
        dest: "{{ intended_configs_root }}/{{ inventory_hostname }}/{{ inventory_hostname }}_intended.conf"




