---
- name: Gather Arista EOS Facts
  hosts: sites_container-lab
  connection: network_cli
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Gather all legacy facts
      arista.eos.eos_facts:
        gather_subset: all

    - name: debug
      debug: 
        var: ansible_net_model
          