---
- name: Gather Arista EOS Facts
  hosts: sites_container_lab
  connection: network_cli
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Gather LLDP Neighbor Information
      arista.eos.eos_facts:
        gather_subset:
          - interfaces

    - name: debug
      debug: 
        var: ansible_net_neighbors
          